language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install
script:
- npm run build

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "travis-ci"
  - git config --local user.email "christoph.birk@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - cd dist
  - zip -r data-inspector-ui-$TRAVIS_TAG.zip *
  - cd ..
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "dist/data-inspector-ui-$TRAVIS_TAG.zip"
  skip_cleanup: true